server:
  port: 8081
  servlet:
    context-path: /demo
    session:
      timeout: 30m
  ssl:
    key-store: sang.p12
    key-alias: tomcathttps
    key-password: 123456
  tomcat:
    uri-encoding: utf-8
    max-threads: 500
book:
  name: 三国演义
  author: 罗贯中
  price: 30

my:
  name: 江南一点雨
  address: China
  favorotes:
    - 足球
    - 徒步
    - Coding

user:
    users:
     - name: 江南一点雨
       address: China
       favorites:
        - 足球
        - 徒步
        - Coding
     - name: sang
       address: GZ
       favorites:
        -阅读
        -吉他
